version: "2"
services:
  postgres:
    image: postgres:14.5-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: khulnasoft
      POSTGRES_DB: khulnasoft
      POSTGRES_PASSWORD: khulnasoft
